// <auto-generated />
using System;
using MathLearnAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MathLearnAPI.Migrations
{
    [DbContext(typeof(acquizdbContext))]
    [Migration("20190613141024_IntroduceQuestionBank")]
    partial class IntroduceQuestionBank
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MathLearnAPI.Models.Knowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("CONTENT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("knowledge");
                });

            modelBuilder.Entity("MathLearnAPI.Models.Qbklink", b =>
                {
                    b.Property<int>("Qbid")
                        .HasColumnName("QBID");

                    b.Property<int>("Kwgid")
                        .HasColumnName("KWGID");

                    b.HasKey("Qbid", "Kwgid");

                    b.HasIndex("Kwgid");

                    b.ToTable("qbklink");
                });

            modelBuilder.Entity("MathLearnAPI.Models.Questionbank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Attachment1")
                        .HasColumnName("ATTACHMENT1");

                    b.Property<byte[]>("Attachment2")
                        .HasColumnName("ATTACHMENT2");

                    b.Property<byte[]>("Attachment3")
                        .HasColumnName("ATTACHMENT3");

                    b.Property<byte[]>("Attachment4")
                        .HasColumnName("ATTACHMENT4");

                    b.Property<byte[]>("Attachment5")
                        .HasColumnName("ATTACHMENT5");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("CONTENT");

                    b.HasKey("Id");

                    b.ToTable("questionbank");
                });

            modelBuilder.Entity("MathLearnAPI.Models.Qbklink", b =>
                {
                    b.HasOne("MathLearnAPI.Models.Knowledge", "Kwg")
                        .WithMany("Qbklink")
                        .HasForeignKey("Kwgid")
                        .HasConstraintName("FK_QstnBkKwdg_KWID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MathLearnAPI.Models.Questionbank", "Qb")
                        .WithMany("Qbklink")
                        .HasForeignKey("Qbid")
                        .HasConstraintName("FK_QstnBkKwdg_QBID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
